# Generated by Django 3.2.7 on 2021-10-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211021_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cart_number',
            new_name='card_number',
        ),
    ]
