# Generated by Django 3.2.7 on 2021-10-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
